sonar.organization=overnightworks
sonar.projectKey=overnightworks_marketplace

sonar.sources=scripts,plugins
sonar.tests=tests
sonar.exclusions=**/*.md
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.qualitygate.wait=true
