#!/usr/bin/env python3
"""Sync Atelier agent definitions from Markdown sources to Codex TOML."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = REPO_ROOT / "plugins" / "atelier" / "agents"
CODEX_TARGET_DIR = REPO_ROOT / "plugins" / "atelier" / ".codex" / "agents"

METADATA_PREFIX = "<!-- atelier-agent "
METADATA_SUFFIX = " -->"
GENERATED_MARKER = "# Generated by scripts/sync_agents.py from "
NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")

READ_TOOLS = ("Read", "Grep", "Glob", "Bash", "Skill")
WRITE_TOOLS = ("Read", "Grep", "Glob", "Bash", "Edit", "Write", "Skill")


@dataclass(frozen=True)
class Agent:
    source_path: Path
    name: str
    description: str
    tools: tuple[str, ...]
    codex_name: str
    codex_sandbox_mode: str
    codex_model_reasoning_effort: str
    codex_nickname_candidates: tuple[str, ...]
    instructions: str


def main() -> int:
    args = parse_args()
    expected = build_expected_codex_agents()
    stale = find_stale_generated_codex_files(expected)
    changed = write_changed_codex_agents(expected, write=not args.check)

    if args.check:
        return report_check_result(changed, stale)

    remove_stale_codex_files(stale)
    report_sync_result(changed + stale)
    return 0


def write_changed_codex_agents(expected: dict[Path, str], *, write: bool) -> list[Path]:
    changed = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return changed


def report_check_result(changed: list[Path], stale: list[Path]) -> int:
    if not changed and not stale:
        print("Generated Codex agents are in sync.")
        return 0
    print("Generated Codex agents are out of sync.", file=sys.stderr)
    for path in changed:
        print(f"- update required: {relative(path)}", file=sys.stderr)
    for path in stale:
        print(f"- stale generated file: {relative(path)}", file=sys.stderr)
    return 1


def remove_stale_codex_files(stale: list[Path]) -> None:
    for path in stale:
        path.unlink()


def report_sync_result(changed: list[Path]) -> None:
    if not changed:
        print("Generated Codex agents already in sync.")
        return
    print("Synced Codex agent translations:")
    for path in changed:
        print(f"- {relative(path)}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate plugins/atelier/.codex/agents/*.toml from agent Markdown."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated Codex agents are not up to date.",
    )
    return parser.parse_args()


def build_expected_codex_agents() -> dict[Path, str]:
    agents = [load_markdown_agent(path) for path in sorted(SOURCE_DIR.glob("*.md"))]
    if not agents:
        raise SystemExit(f"No source agents found in {relative(SOURCE_DIR)}")
    return {
        CODEX_TARGET_DIR / f"{agent.codex_name.replace('_', '-')}.toml": render_codex_toml(agent)
        for agent in agents
    }


def load_markdown_agent(path: Path) -> Agent:
    frontmatter, body = split_frontmatter(path)
    name = require_frontmatter_string(frontmatter, "name", path)
    description = require_frontmatter_string(frontmatter, "description", path)
    if NAME_RE.fullmatch(name) is None:
        raise SystemExit(f"{relative(path)} field `name` must be lower hyphen-case.")

    tools = frontmatter.get("tools")
    if not isinstance(tools, list) or not all(isinstance(tool, str) and tool for tool in tools):
        raise SystemExit(f"{relative(path)} field `tools` must be a list of strings.")

    metadata, instructions = split_metadata(body, path)
    codex_name = require_metadata_string(metadata, "codex_name", path)
    codex_sandbox_mode = require_metadata_string(metadata, "codex_sandbox_mode", path)
    codex_model_reasoning_effort = require_metadata_string(
        metadata,
        "codex_model_reasoning_effort",
        path,
    )
    codex_nickname_candidates = metadata.get("codex_nickname_candidates", [])
    if not isinstance(codex_nickname_candidates, list) or not all(
        isinstance(value, str) and value.strip() for value in codex_nickname_candidates
    ):
        raise SystemExit(
            f"{relative(path)} metadata `codex_nickname_candidates` must be strings."
        )

    expected_name = codex_name.replace("_", "-")
    if expected_name != name:
        raise SystemExit(
            f"{relative(path)} name mismatch: frontmatter name {name!r} should match "
            f"metadata codex_name {codex_name!r} as {expected_name!r}."
        )
    validate_tool_mapping(path, tuple(tools), codex_sandbox_mode)

    return Agent(
        source_path=path,
        name=name,
        description=description,
        tools=tuple(tools),
        codex_name=codex_name,
        codex_sandbox_mode=codex_sandbox_mode,
        codex_model_reasoning_effort=codex_model_reasoning_effort,
        codex_nickname_candidates=tuple(codex_nickname_candidates),
        instructions=instructions.strip(),
    )


def split_frontmatter(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise SystemExit(f"{relative(path)} must start with YAML frontmatter.")

    try:
        end = lines.index("---", 1)
    except ValueError:
        raise SystemExit(f"{relative(path)} is missing closing frontmatter marker.")

    frontmatter = parse_simple_yaml(lines[1:end], path)
    body = "\n".join(lines[end + 1 :]).strip()
    return frontmatter, body


def parse_simple_yaml(lines: list[str], path: Path) -> dict[str, Any]:
    payload: dict[str, Any] = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip():
            index += 1
            continue
        if line.startswith("  - "):
            raise SystemExit(f"{relative(path)} has a list item without a key: {line}")
        if ":" not in line:
            raise SystemExit(f"{relative(path)} has unsupported frontmatter line: {line}")
        key, raw_value = line.split(":", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        if raw_value:
            payload[key] = parse_scalar(raw_value)
            index += 1
            continue
        values = []
        index += 1
        while index < len(lines) and lines[index].startswith("  - "):
            values.append(parse_scalar(lines[index][4:].strip()))
            index += 1
        payload[key] = values
    return payload


def parse_scalar(value: str) -> str:
    # A value starting with `"` is a JSON string literal, which json.loads can
    # only resolve to a Python str; a leading `'` is invalid JSON and raises
    # instead of resolving. Neither path can yield a non-string result.
    if value and value[0] in {'"', "'"}:
        return json.loads(value)
    return value


def split_metadata(body: str, path: Path) -> tuple[dict[str, Any], str]:
    stripped = body.lstrip()
    if not stripped.startswith(METADATA_PREFIX):
        raise SystemExit(
            f"{relative(path)} must include an `{METADATA_PREFIX.strip()}` metadata comment."
        )
    end = stripped.find(METADATA_SUFFIX)
    if end == -1:
        raise SystemExit(f"{relative(path)} has an unterminated metadata comment.")
    raw_metadata = stripped[len(METADATA_PREFIX) : end]
    try:
        metadata = json.loads(raw_metadata)
    except json.JSONDecodeError as error:
        raise SystemExit(f"{relative(path)} has invalid agent metadata JSON: {error}") from error
    if not isinstance(metadata, dict):
        raise SystemExit(f"{relative(path)} metadata must be a JSON object.")
    instructions = stripped[end + len(METADATA_SUFFIX) :].strip()
    if not instructions:
        raise SystemExit(f"{relative(path)} must include agent instructions after metadata.")
    return metadata, instructions


def require_frontmatter_string(payload: dict[str, Any], key: str, path: Path) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise SystemExit(f"{relative(path)} frontmatter `{key}` must be a non-empty string.")
    return value.strip()


def require_metadata_string(payload: dict[str, Any], key: str, path: Path) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise SystemExit(f"{relative(path)} metadata `{key}` must be a non-empty string.")
    return value.strip()


def validate_tool_mapping(path: Path, tools: tuple[str, ...], sandbox_mode: str) -> None:
    expected = tools_for_sandbox(sandbox_mode)
    if tools != expected:
        raise SystemExit(
            f"{relative(path)} tools {tools!r} do not match sandbox mode "
            f"{sandbox_mode!r}; expected {expected!r}."
        )


def tools_for_sandbox(sandbox_mode: str) -> tuple[str, ...]:
    if sandbox_mode == "read-only":
        return READ_TOOLS
    if sandbox_mode == "workspace-write":
        return WRITE_TOOLS
    raise SystemExit(
        f"Unsupported codex_sandbox_mode {sandbox_mode!r}. Add an explicit tool mapping."
    )


def render_codex_toml(agent: Agent) -> str:
    source = relative(agent.source_path)
    lines = [
        f"{GENERATED_MARKER}{source}. Do not edit by hand.",
        f"name = {toml_string(agent.codex_name)}",
        f"description = {toml_string(agent.description)}",
        f"model_reasoning_effort = {toml_string(agent.codex_model_reasoning_effort)}",
        f"sandbox_mode = {toml_string(agent.codex_sandbox_mode)}",
        f"nickname_candidates = {toml_array(agent.codex_nickname_candidates)}",
        f"developer_instructions = {toml_string(agent.instructions)}",
        "",
    ]
    return "\n".join(lines)


def toml_string(value: str) -> str:
    return json.dumps(value)


def toml_array(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(toml_string(value) for value in values) + "]"


def find_stale_generated_codex_files(expected: dict[Path, str]) -> list[Path]:
    expected_paths = set(expected)
    stale = []
    if not CODEX_TARGET_DIR.exists():
        return stale
    for path in sorted(CODEX_TARGET_DIR.glob("*.toml")):
        if path in expected_paths:
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if GENERATED_MARKER in content:
            stale.append(path)
    return stale


def relative(path: Path) -> str:
    # SOURCE_DIR and CODEX_TARGET_DIR are both derived from REPO_ROOT, so
    # every path this module prints is guaranteed to live under it.
    return str(path.relative_to(REPO_ROOT))


if __name__ == "__main__":  # pragma: no cover - process entry point, no logic of its own
    raise SystemExit(main())
